### ISSUE TITLE
[UI] AdminViewRoom

### ISSUE THREAD

**Issue by ListKelvin** [KyohagiErika/rode-fe#20]
In file FilterQues the UI of question filter dissimilar to figma 
![image](https://user-images.githubusercontent.com/92376692/226777762-fea759c5-9179-4bb6-bad5-8364ed694ab0.png)

**Comment by ngockim109** [comment]
![image](https://user-images.githubusercontent.com/96067465/226817037-ba03f54d-45cb-4fa6-bcc4-256b83f424e3.png)
![image](https://user-images.githubusercontent.com/96067465/226817079-a1e84b51-d2fa-4a12-ae7f-cc5c42876ded.png)
t chỉnh vầy được hong á

**Comment by ListKelvin** [comment]
oke nha
